name: Curriculitae
favicon: null
layout_spectrum: 0.9719815289136022
typography_spectrum: 0.6401651543565094
title: Lead iOS Developer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5fafe'
    - '#cecccf'
    - '#121318'
    - '#636260'
    - '#a4a094'
  brandStrength: 0.20755369868129492
  lightness: 0.3035026977304369
  saturation: 0.1136892894282937
  rhythmicContrast: 0.6974530420266092
purpose: []
